# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - wsl
    - varnamelen
    # Deprecated
    - interfacer
    - maligned
    - scopelint
    - golint

output:
  sort-results: true

service:
  golangci-lint-version: 1.46.x # use the fixed version to not introduce new linters unexpectedly
