package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/SamHennessy/hlive/hhtml"
)

// breakCommentAt80 breaks a long comment into lines of maximum 80 characters
func breakCommentAt80(text string) string {
	if len(text) <= 80 {
		return text
	}

	var lines []string
	words := strings.Fields(text)
	currentLine := ""

	for _, word := range words {
		if len(currentLine)+len(word)+1 <= 80 {
			if currentLine != "" {
				currentLine += " " + word
			} else {
				currentLine = word
			}
		} else {
			if currentLine != "" {
				lines = append(lines, currentLine)
			}
			currentLine = word
		}
	}

	if currentLine != "" {
		lines = append(lines, currentLine)
	}

	return strings.Join(lines, "\n// ")
}

func generateTags() {
	// Create the tags.go file directly using the structure from DataAll

	f, err := os.Create("../../tags.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	// Write generated file header
	fmt.Fprintln(f, "// Code generated by cmd/tags/tags_gen.go - DO NOT EDIT")
	fmt.Fprintln(f, "// Source: hhtml/cmd/tags/tags_gen.go")
	fmt.Fprintln(f)

	// Write package declaration and imports
	fmt.Fprintln(f, "package hhtml")
	fmt.Fprintln(f)
	fmt.Fprintln(f, `import "github.com/SamHennessy/hlive"`)
	fmt.Fprintln(f)

	// Get all tag names from DataAll and sort them
	var tagNames []string
	for tagName := range hhtml.DataAll {
		tagNames = append(tagNames, tagName)
	}
	sort.Strings(tagNames)

	// Track valid tags and their function names for the map
	var validTags []string
	var validFunctionNames []string

	// Generate functions for each tag
	for _, tag := range tagNames {
		tagData := hhtml.DataAll[tag]

		// Skip deprecated tags
		if tagData.Deprecated {
			continue
		}

		// Get function name (capitalize first letter)
		funcName := strings.ToUpper(tag[:1]) + tag[1:]
		if tag == "*" {
			continue
		}

		// Track valid tags and function names
		validTags = append(validTags, tag)
		validFunctionNames = append(validFunctionNames, funcName)

		// Get description from DataAll
		shortDesc := tagData.DescriptionShort
		if shortDesc == "" {
			shortDesc = fmt.Sprintf("%s tag - represents a %s element", funcName, tag)
		}

		// Start comment with function name and short description
		description := fmt.Sprintf("%s - %s", funcName, shortDesc)

		// Add long description if available
		if tagData.DescriptionLong != "" {
			description += "\n//\n// " + breakCommentAt80(tagData.DescriptionLong)
		}

		// Add experimental warning if needed
		if tagData.Experimental {
			description += "\n// Experimental: This element is experimental and may not be supported in all browsers."
		}

		// Write function
		fmt.Fprintf(f, "// %s\n", description)
		fmt.Fprintf(f, "func %s(elements ...any) hlive.Adder {\n", funcName)
		fmt.Fprintf(f, "\treturn tagBuilder(%q, elements...)\n", tag)
		fmt.Fprintln(f, "}")
		fmt.Fprintln(f)
	}

	// Generate the tag function map
	fmt.Fprintln(f, "// TagFunctions maps tag names to their corresponding tag functions")
	fmt.Fprintln(f, "var TagFunctions = map[string]func(...any) hlive.Adder{")
	for i, tag := range validTags {
		funcName := validFunctionNames[i]
		fmt.Fprintf(f, "\t%q: %s,\n", tag, funcName)
	}
	fmt.Fprintln(f, "}")

	fmt.Println("Generated tags.go successfully!")
}

// Run this function to generate tags.go
func main() {
	generateTags()
}
