// Code generated by cmd/attrs/attrs_gen.go - DO NOT EDIT
// Source: hhtml/cmd/attrs/attrs_gen.go

package hhtml

import "github.com/SamHennessy/hlive"

// AbbrAttr represents a abbr attribute
func AbbrAttr(value string) *hlive.Attribute {
	return hlive.NewAttribute("abbr", value)
}

// Accept represents a accept attribute
func Accept(value string) *hlive.Attribute {
	return hlive.NewAttribute("accept", value)
}

// AcceptCharset represents a accept-charset attribute
func AcceptCharset(value string) *hlive.Attribute {
	return hlive.NewAttribute("accept-charset", value)
}

// Accesskey represents a accesskey attribute
func Accesskey(value string) *hlive.Attribute {
	return hlive.NewAttribute("accesskey", value)
}

// Allow represents a allow attribute
func Allow(value string) *hlive.Attribute {
	return hlive.NewAttribute("allow", value)
}

// Allowfullscreen represents a allowfullscreen attribute
func Allowfullscreen(value string) *hlive.Attribute {
	return hlive.NewAttribute("allowfullscreen", value)
}

// Alt represents a alt attribute
func Alt(value string) *hlive.Attribute {
	return hlive.NewAttribute("alt", value)
}

// Anchor represents a anchor attribute
func Anchor(value string) *hlive.Attribute {
	return hlive.NewAttribute("anchor", value)
}

// As represents a as attribute
func As(value string) *hlive.Attribute {
	return hlive.NewAttribute("as", value)
}

// Async represents a async attribute
func Async(value string) *hlive.Attribute {
	return hlive.NewAttribute("async", value)
}

// Attributionsrc represents a attributionsrc attribute
func Attributionsrc(value string) *hlive.Attribute {
	return hlive.NewAttribute("attributionsrc", value)
}

// Autocapitalize represents a autocapitalize attribute
func Autocapitalize(value string) *hlive.Attribute {
	return hlive.NewAttribute("autocapitalize", value)
}

// Autocomplete represents a autocomplete attribute
func Autocomplete(value string) *hlive.Attribute {
	return hlive.NewAttribute("autocomplete", value)
}

// Autocorrect represents a autocorrect attribute
func Autocorrect(value string) *hlive.Attribute {
	return hlive.NewAttribute("autocorrect", value)
}

// Autofocus represents a autofocus attribute
func Autofocus(value string) *hlive.Attribute {
	return hlive.NewAttribute("autofocus", value)
}

// Autoplay represents a autoplay attribute
func Autoplay(value string) *hlive.Attribute {
	return hlive.NewAttribute("autoplay", value)
}

// Blocking represents a blocking attribute
func Blocking(value string) *hlive.Attribute {
	return hlive.NewAttribute("blocking", value)
}

// Browsingtopics represents a browsingtopics attribute
func Browsingtopics(value string) *hlive.Attribute {
	return hlive.NewAttribute("browsingtopics", value)
}

// Capture represents a capture attribute
func Capture(value string) *hlive.Attribute {
	return hlive.NewAttribute("capture", value)
}

// Charset represents a charset attribute
func Charset(value string) *hlive.Attribute {
	return hlive.NewAttribute("charset", value)
}

// Checked represents a checked attribute
func Checked(value string) *hlive.Attribute {
	return hlive.NewAttribute("checked", value)
}

// CiteAttr represents a cite attribute
func CiteAttr(value string) *hlive.Attribute {
	return hlive.NewAttribute("cite", value)
}

// Class represents a class attribute
func Class(value string) *hlive.Attribute {
	return hlive.NewAttribute("class", value)
}

// Cols represents a cols attribute
func Cols(value string) *hlive.Attribute {
	return hlive.NewAttribute("cols", value)
}

// Colspan represents a colspan attribute
func Colspan(value string) *hlive.Attribute {
	return hlive.NewAttribute("colspan", value)
}

// Content represents a content attribute
func Content(value string) *hlive.Attribute {
	return hlive.NewAttribute("content", value)
}

// Contenteditable represents a contenteditable attribute
func Contenteditable(value string) *hlive.Attribute {
	return hlive.NewAttribute("contenteditable", value)
}

// Controls represents a controls attribute
func Controls(value string) *hlive.Attribute {
	return hlive.NewAttribute("controls", value)
}

// Controlslist represents a controlslist attribute
func Controlslist(value string) *hlive.Attribute {
	return hlive.NewAttribute("controlslist", value)
}

// Coords represents a coords attribute
func Coords(value string) *hlive.Attribute {
	return hlive.NewAttribute("coords", value)
}

// Credentialless represents a credentialless attribute
func Credentialless(value string) *hlive.Attribute {
	return hlive.NewAttribute("credentialless", value)
}

// Crossorigin represents a crossorigin attribute
func Crossorigin(value string) *hlive.Attribute {
	return hlive.NewAttribute("crossorigin", value)
}

// Csp represents a csp attribute
func Csp(value string) *hlive.Attribute {
	return hlive.NewAttribute("csp", value)
}

// DataAttr represents a data attribute
func DataAttr(value string) *hlive.Attribute {
	return hlive.NewAttribute("data", value)
}

// Datetime represents a datetime attribute
func Datetime(value string) *hlive.Attribute {
	return hlive.NewAttribute("datetime", value)
}

// Decoding represents a decoding attribute
func Decoding(value string) *hlive.Attribute {
	return hlive.NewAttribute("decoding", value)
}

// Default represents a default attribute
func Default(value string) *hlive.Attribute {
	return hlive.NewAttribute("default", value)
}

// Defer represents a defer attribute
func Defer(value string) *hlive.Attribute {
	return hlive.NewAttribute("defer", value)
}

// Dir represents a dir attribute
func Dir(value string) *hlive.Attribute {
	return hlive.NewAttribute("dir", value)
}

// Dirname represents a dirname attribute
func Dirname(value string) *hlive.Attribute {
	return hlive.NewAttribute("dirname", value)
}

// Disabled represents a disabled attribute
func Disabled(value string) *hlive.Attribute {
	return hlive.NewAttribute("disabled", value)
}

// Disablepictureinpicture represents a disablepictureinpicture attribute
func Disablepictureinpicture(value string) *hlive.Attribute {
	return hlive.NewAttribute("disablepictureinpicture", value)
}

// Disableremoteplayback represents a disableremoteplayback attribute
func Disableremoteplayback(value string) *hlive.Attribute {
	return hlive.NewAttribute("disableremoteplayback", value)
}

// Download represents a download attribute
func Download(value string) *hlive.Attribute {
	return hlive.NewAttribute("download", value)
}

// Draggable represents a draggable attribute
func Draggable(value string) *hlive.Attribute {
	return hlive.NewAttribute("draggable", value)
}

// Elementtiming represents a elementtiming attribute
func Elementtiming(value string) *hlive.Attribute {
	return hlive.NewAttribute("elementtiming", value)
}

// Enterkeyhint represents a enterkeyhint attribute
func Enterkeyhint(value string) *hlive.Attribute {
	return hlive.NewAttribute("enterkeyhint", value)
}

// Exportparts represents a exportparts attribute
func Exportparts(value string) *hlive.Attribute {
	return hlive.NewAttribute("exportparts", value)
}

// Fetchpriority represents a fetchpriority attribute
func Fetchpriority(value string) *hlive.Attribute {
	return hlive.NewAttribute("fetchpriority", value)
}

// For represents a for attribute
func For(value string) *hlive.Attribute {
	return hlive.NewAttribute("for", value)
}

// FormAttr represents a form attribute
func FormAttr(value string) *hlive.Attribute {
	return hlive.NewAttribute("form", value)
}

// Formaction represents a formaction attribute
func Formaction(value string) *hlive.Attribute {
	return hlive.NewAttribute("formaction", value)
}

// Formenctype represents a formenctype attribute
func Formenctype(value string) *hlive.Attribute {
	return hlive.NewAttribute("formenctype", value)
}

// Formmethod represents a formmethod attribute
func Formmethod(value string) *hlive.Attribute {
	return hlive.NewAttribute("formmethod", value)
}

// Formnovalidate represents a formnovalidate attribute
func Formnovalidate(value string) *hlive.Attribute {
	return hlive.NewAttribute("formnovalidate", value)
}

// Formtarget represents a formtarget attribute
func Formtarget(value string) *hlive.Attribute {
	return hlive.NewAttribute("formtarget", value)
}

// Headers represents a headers attribute
func Headers(value string) *hlive.Attribute {
	return hlive.NewAttribute("headers", value)
}

// Height represents a height attribute
func Height(value string) *hlive.Attribute {
	return hlive.NewAttribute("height", value)
}

// Hidden represents a hidden attribute
func Hidden(value string) *hlive.Attribute {
	return hlive.NewAttribute("hidden", value)
}

// High represents a high attribute
func High(value string) *hlive.Attribute {
	return hlive.NewAttribute("high", value)
}

// Href represents a href attribute
func Href(value string) *hlive.Attribute {
	return hlive.NewAttribute("href", value)
}

// Hreflang represents a hreflang attribute
func Hreflang(value string) *hlive.Attribute {
	return hlive.NewAttribute("hreflang", value)
}

// HttpEquiv represents a http-equiv attribute
func HttpEquiv(value string) *hlive.Attribute {
	return hlive.NewAttribute("http-equiv", value)
}

// Id represents a id attribute
func Id(value string) *hlive.Attribute {
	return hlive.NewAttribute("id", value)
}

// Imagesizes represents a imagesizes attribute
func Imagesizes(value string) *hlive.Attribute {
	return hlive.NewAttribute("imagesizes", value)
}

// Imagesrcset represents a imagesrcset attribute
func Imagesrcset(value string) *hlive.Attribute {
	return hlive.NewAttribute("imagesrcset", value)
}

// Inert represents a inert attribute
func Inert(value string) *hlive.Attribute {
	return hlive.NewAttribute("inert", value)
}

// Inputmode represents a inputmode attribute
func Inputmode(value string) *hlive.Attribute {
	return hlive.NewAttribute("inputmode", value)
}

// Integrity represents a integrity attribute
func Integrity(value string) *hlive.Attribute {
	return hlive.NewAttribute("integrity", value)
}

// Is represents a is attribute
func Is(value string) *hlive.Attribute {
	return hlive.NewAttribute("is", value)
}

// Ismap represents a ismap attribute
func Ismap(value string) *hlive.Attribute {
	return hlive.NewAttribute("ismap", value)
}

// Itemid represents a itemid attribute
func Itemid(value string) *hlive.Attribute {
	return hlive.NewAttribute("itemid", value)
}

// Itemprop represents a itemprop attribute
func Itemprop(value string) *hlive.Attribute {
	return hlive.NewAttribute("itemprop", value)
}

// Itemref represents a itemref attribute
func Itemref(value string) *hlive.Attribute {
	return hlive.NewAttribute("itemref", value)
}

// Itemscope represents a itemscope attribute
func Itemscope(value string) *hlive.Attribute {
	return hlive.NewAttribute("itemscope", value)
}

// Itemtype represents a itemtype attribute
func Itemtype(value string) *hlive.Attribute {
	return hlive.NewAttribute("itemtype", value)
}

// Kind represents a kind attribute
func Kind(value string) *hlive.Attribute {
	return hlive.NewAttribute("kind", value)
}

// LabelAttr represents a label attribute
func LabelAttr(value string) *hlive.Attribute {
	return hlive.NewAttribute("label", value)
}

// Lang represents a lang attribute
func Lang(value string) *hlive.Attribute {
	return hlive.NewAttribute("lang", value)
}

// List represents a list attribute
func List(value string) *hlive.Attribute {
	return hlive.NewAttribute("list", value)
}

// Loading represents a loading attribute
func Loading(value string) *hlive.Attribute {
	return hlive.NewAttribute("loading", value)
}

// Loop represents a loop attribute
func Loop(value string) *hlive.Attribute {
	return hlive.NewAttribute("loop", value)
}

// Low represents a low attribute
func Low(value string) *hlive.Attribute {
	return hlive.NewAttribute("low", value)
}

// Max represents a max attribute
func Max(value string) *hlive.Attribute {
	return hlive.NewAttribute("max", value)
}

// Maxlength represents a maxlength attribute
func Maxlength(value string) *hlive.Attribute {
	return hlive.NewAttribute("maxlength", value)
}

// Media represents a media attribute
func Media(value string) *hlive.Attribute {
	return hlive.NewAttribute("media", value)
}

// Min represents a min attribute
func Min(value string) *hlive.Attribute {
	return hlive.NewAttribute("min", value)
}

// Minlength represents a minlength attribute
func Minlength(value string) *hlive.Attribute {
	return hlive.NewAttribute("minlength", value)
}

// Multiple represents a multiple attribute
func Multiple(value string) *hlive.Attribute {
	return hlive.NewAttribute("multiple", value)
}

// Muted represents a muted attribute
func Muted(value string) *hlive.Attribute {
	return hlive.NewAttribute("muted", value)
}

// Name represents a name attribute
func Name(value string) *hlive.Attribute {
	return hlive.NewAttribute("name", value)
}

// Nomodule represents a nomodule attribute
func Nomodule(value string) *hlive.Attribute {
	return hlive.NewAttribute("nomodule", value)
}

// Nonce represents a nonce attribute
func Nonce(value string) *hlive.Attribute {
	return hlive.NewAttribute("nonce", value)
}

// Onafterprint represents a onafterprint attribute
func Onafterprint(value string) *hlive.Attribute {
	return hlive.NewAttribute("onafterprint", value)
}

// Onbeforeprint represents a onbeforeprint attribute
func Onbeforeprint(value string) *hlive.Attribute {
	return hlive.NewAttribute("onbeforeprint", value)
}

// Onbeforeunload represents a onbeforeunload attribute
func Onbeforeunload(value string) *hlive.Attribute {
	return hlive.NewAttribute("onbeforeunload", value)
}

// Onblur represents a onblur attribute
func Onblur(value string) *hlive.Attribute {
	return hlive.NewAttribute("onblur", value)
}

// Onerror represents a onerror attribute
func Onerror(value string) *hlive.Attribute {
	return hlive.NewAttribute("onerror", value)
}

// Onfocus represents a onfocus attribute
func Onfocus(value string) *hlive.Attribute {
	return hlive.NewAttribute("onfocus", value)
}

// Onhashchange represents a onhashchange attribute
func Onhashchange(value string) *hlive.Attribute {
	return hlive.NewAttribute("onhashchange", value)
}

// Onlanguagechange represents a onlanguagechange attribute
func Onlanguagechange(value string) *hlive.Attribute {
	return hlive.NewAttribute("onlanguagechange", value)
}

// Onload represents a onload attribute
func Onload(value string) *hlive.Attribute {
	return hlive.NewAttribute("onload", value)
}

// Onmessage represents a onmessage attribute
func Onmessage(value string) *hlive.Attribute {
	return hlive.NewAttribute("onmessage", value)
}

// Onoffline represents a onoffline attribute
func Onoffline(value string) *hlive.Attribute {
	return hlive.NewAttribute("onoffline", value)
}

// Ononline represents a ononline attribute
func Ononline(value string) *hlive.Attribute {
	return hlive.NewAttribute("ononline", value)
}

// Onpopstate represents a onpopstate attribute
func Onpopstate(value string) *hlive.Attribute {
	return hlive.NewAttribute("onpopstate", value)
}

// Onresize represents a onresize attribute
func Onresize(value string) *hlive.Attribute {
	return hlive.NewAttribute("onresize", value)
}

// Onstorage represents a onstorage attribute
func Onstorage(value string) *hlive.Attribute {
	return hlive.NewAttribute("onstorage", value)
}

// Onunload represents a onunload attribute
func Onunload(value string) *hlive.Attribute {
	return hlive.NewAttribute("onunload", value)
}

// Open represents a open attribute
func Open(value string) *hlive.Attribute {
	return hlive.NewAttribute("open", value)
}

// Optimum represents a optimum attribute
func Optimum(value string) *hlive.Attribute {
	return hlive.NewAttribute("optimum", value)
}

// Part represents a part attribute
func Part(value string) *hlive.Attribute {
	return hlive.NewAttribute("part", value)
}

// Pattern represents a pattern attribute
func Pattern(value string) *hlive.Attribute {
	return hlive.NewAttribute("pattern", value)
}

// Ping represents a ping attribute
func Ping(value string) *hlive.Attribute {
	return hlive.NewAttribute("ping", value)
}

// Placeholder represents a placeholder attribute
func Placeholder(value string) *hlive.Attribute {
	return hlive.NewAttribute("placeholder", value)
}

// Playsinline represents a playsinline attribute
func Playsinline(value string) *hlive.Attribute {
	return hlive.NewAttribute("playsinline", value)
}

// Popover represents a popover attribute
func Popover(value string) *hlive.Attribute {
	return hlive.NewAttribute("popover", value)
}

// Popovertarget represents a popovertarget attribute
func Popovertarget(value string) *hlive.Attribute {
	return hlive.NewAttribute("popovertarget", value)
}

// Popovertargetaction represents a popovertargetaction attribute
func Popovertargetaction(value string) *hlive.Attribute {
	return hlive.NewAttribute("popovertargetaction", value)
}

// Poster represents a poster attribute
func Poster(value string) *hlive.Attribute {
	return hlive.NewAttribute("poster", value)
}

// Preload represents a preload attribute
func Preload(value string) *hlive.Attribute {
	return hlive.NewAttribute("preload", value)
}

// Readonly represents a readonly attribute
func Readonly(value string) *hlive.Attribute {
	return hlive.NewAttribute("readonly", value)
}

// Referrerpolicy represents a referrerpolicy attribute
func Referrerpolicy(value string) *hlive.Attribute {
	return hlive.NewAttribute("referrerpolicy", value)
}

// Rel represents a rel attribute
func Rel(value string) *hlive.Attribute {
	return hlive.NewAttribute("rel", value)
}

// Required represents a required attribute
func Required(value string) *hlive.Attribute {
	return hlive.NewAttribute("required", value)
}

// Reversed represents a reversed attribute
func Reversed(value string) *hlive.Attribute {
	return hlive.NewAttribute("reversed", value)
}

// Rows represents a rows attribute
func Rows(value string) *hlive.Attribute {
	return hlive.NewAttribute("rows", value)
}

// Rowspan represents a rowspan attribute
func Rowspan(value string) *hlive.Attribute {
	return hlive.NewAttribute("rowspan", value)
}

// Sandbox represents a sandbox attribute
func Sandbox(value string) *hlive.Attribute {
	return hlive.NewAttribute("sandbox", value)
}

// Scope represents a scope attribute
func Scope(value string) *hlive.Attribute {
	return hlive.NewAttribute("scope", value)
}

// Selected represents a selected attribute
func Selected(value string) *hlive.Attribute {
	return hlive.NewAttribute("selected", value)
}

// Shadowrootclonable represents a shadowrootclonable attribute
func Shadowrootclonable(value string) *hlive.Attribute {
	return hlive.NewAttribute("shadowrootclonable", value)
}

// Shadowrootdelegatesfocus represents a shadowrootdelegatesfocus attribute
func Shadowrootdelegatesfocus(value string) *hlive.Attribute {
	return hlive.NewAttribute("shadowrootdelegatesfocus", value)
}

// Shadowrootmode represents a shadowrootmode attribute
func Shadowrootmode(value string) *hlive.Attribute {
	return hlive.NewAttribute("shadowrootmode", value)
}

// Shadowrootserializable represents a shadowrootserializable attribute
func Shadowrootserializable(value string) *hlive.Attribute {
	return hlive.NewAttribute("shadowrootserializable", value)
}

// Shape represents a shape attribute
func Shape(value string) *hlive.Attribute {
	return hlive.NewAttribute("shape", value)
}

// Size represents a size attribute
func Size(value string) *hlive.Attribute {
	return hlive.NewAttribute("size", value)
}

// Sizes represents a sizes attribute
func Sizes(value string) *hlive.Attribute {
	return hlive.NewAttribute("sizes", value)
}

// SlotAttr represents a slot attribute
func SlotAttr(value string) *hlive.Attribute {
	return hlive.NewAttribute("slot", value)
}

// SpanAttr represents a span attribute
func SpanAttr(value string) *hlive.Attribute {
	return hlive.NewAttribute("span", value)
}

// Spellcheck represents a spellcheck attribute
func Spellcheck(value string) *hlive.Attribute {
	return hlive.NewAttribute("spellcheck", value)
}

// Src represents a src attribute
func Src(value string) *hlive.Attribute {
	return hlive.NewAttribute("src", value)
}

// Srcdoc represents a srcdoc attribute
func Srcdoc(value string) *hlive.Attribute {
	return hlive.NewAttribute("srcdoc", value)
}

// Srclang represents a srclang attribute
func Srclang(value string) *hlive.Attribute {
	return hlive.NewAttribute("srclang", value)
}

// Srcset represents a srcset attribute
func Srcset(value string) *hlive.Attribute {
	return hlive.NewAttribute("srcset", value)
}

// Start represents a start attribute
func Start(value string) *hlive.Attribute {
	return hlive.NewAttribute("start", value)
}

// Step represents a step attribute
func Step(value string) *hlive.Attribute {
	return hlive.NewAttribute("step", value)
}

// StyleAttr represents a style attribute
func StyleAttr(value string) *hlive.Attribute {
	return hlive.NewAttribute("style", value)
}

// Tabindex represents a tabindex attribute
func Tabindex(value string) *hlive.Attribute {
	return hlive.NewAttribute("tabindex", value)
}

// Target represents a target attribute
func Target(value string) *hlive.Attribute {
	return hlive.NewAttribute("target", value)
}

// TitleAttr represents a title attribute
func TitleAttr(value string) *hlive.Attribute {
	return hlive.NewAttribute("title", value)
}

// Translate represents a translate attribute
func Translate(value string) *hlive.Attribute {
	return hlive.NewAttribute("translate", value)
}

// Type represents a type attribute
func Type(value string) *hlive.Attribute {
	return hlive.NewAttribute("type", value)
}

// Usemap represents a usemap attribute
func Usemap(value string) *hlive.Attribute {
	return hlive.NewAttribute("usemap", value)
}

// Value represents a value attribute
func Value(value string) *hlive.Attribute {
	return hlive.NewAttribute("value", value)
}

// Virtualkeyboardpolicy represents a virtualkeyboardpolicy attribute
func Virtualkeyboardpolicy(value string) *hlive.Attribute {
	return hlive.NewAttribute("virtualkeyboardpolicy", value)
}

// Width represents a width attribute
func Width(value string) *hlive.Attribute {
	return hlive.NewAttribute("width", value)
}

// Wrap represents a wrap attribute
func Wrap(value string) *hlive.Attribute {
	return hlive.NewAttribute("wrap", value)
}

// Writingsuggestions represents a writingsuggestions attribute
func Writingsuggestions(value string) *hlive.Attribute {
	return hlive.NewAttribute("writingsuggestions", value)
}

// Xmlns represents a xmlns attribute
func Xmlns(value string) *hlive.Attribute {
	return hlive.NewAttribute("xmlns", value)
}

// AttrFunctionNames maps attribute names to their corresponding function names
var AttrFunctionNames = map[string]string{
	"abbr":                     "AbbrAttr",
	"accept":                   "Accept",
	"accept-charset":           "AcceptCharset",
	"accesskey":                "Accesskey",
	"allow":                    "Allow",
	"allowfullscreen":          "Allowfullscreen",
	"alt":                      "Alt",
	"anchor":                   "Anchor",
	"as":                       "As",
	"async":                    "Async",
	"attributionsrc":           "Attributionsrc",
	"autocapitalize":           "Autocapitalize",
	"autocomplete":             "Autocomplete",
	"autocorrect":              "Autocorrect",
	"autofocus":                "Autofocus",
	"autoplay":                 "Autoplay",
	"blocking":                 "Blocking",
	"browsingtopics":           "Browsingtopics",
	"capture":                  "Capture",
	"charset":                  "Charset",
	"checked":                  "Checked",
	"cite":                     "CiteAttr",
	"class":                    "Class",
	"cols":                     "Cols",
	"colspan":                  "Colspan",
	"content":                  "Content",
	"contenteditable":          "Contenteditable",
	"controls":                 "Controls",
	"controlslist":             "Controlslist",
	"coords":                   "Coords",
	"credentialless":           "Credentialless",
	"crossorigin":              "Crossorigin",
	"csp":                      "Csp",
	"data":                     "DataAttr",
	"datetime":                 "Datetime",
	"decoding":                 "Decoding",
	"default":                  "Default",
	"defer":                    "Defer",
	"dir":                      "Dir",
	"dirname":                  "Dirname",
	"disabled":                 "Disabled",
	"disablepictureinpicture":  "Disablepictureinpicture",
	"disableremoteplayback":    "Disableremoteplayback",
	"download":                 "Download",
	"draggable":                "Draggable",
	"elementtiming":            "Elementtiming",
	"enterkeyhint":             "Enterkeyhint",
	"exportparts":              "Exportparts",
	"fetchpriority":            "Fetchpriority",
	"for":                      "For",
	"form":                     "FormAttr",
	"formaction":               "Formaction",
	"formenctype":              "Formenctype",
	"formmethod":               "Formmethod",
	"formnovalidate":           "Formnovalidate",
	"formtarget":               "Formtarget",
	"headers":                  "Headers",
	"height":                   "Height",
	"hidden":                   "Hidden",
	"high":                     "High",
	"href":                     "Href",
	"hreflang":                 "Hreflang",
	"http-equiv":               "HttpEquiv",
	"id":                       "Id",
	"imagesizes":               "Imagesizes",
	"imagesrcset":              "Imagesrcset",
	"inert":                    "Inert",
	"inputmode":                "Inputmode",
	"integrity":                "Integrity",
	"is":                       "Is",
	"ismap":                    "Ismap",
	"itemid":                   "Itemid",
	"itemprop":                 "Itemprop",
	"itemref":                  "Itemref",
	"itemscope":                "Itemscope",
	"itemtype":                 "Itemtype",
	"kind":                     "Kind",
	"label":                    "LabelAttr",
	"lang":                     "Lang",
	"list":                     "List",
	"loading":                  "Loading",
	"loop":                     "Loop",
	"low":                      "Low",
	"max":                      "Max",
	"maxlength":                "Maxlength",
	"media":                    "Media",
	"min":                      "Min",
	"minlength":                "Minlength",
	"multiple":                 "Multiple",
	"muted":                    "Muted",
	"name":                     "Name",
	"nomodule":                 "Nomodule",
	"nonce":                    "Nonce",
	"onafterprint":             "Onafterprint",
	"onbeforeprint":            "Onbeforeprint",
	"onbeforeunload":           "Onbeforeunload",
	"onblur":                   "Onblur",
	"onerror":                  "Onerror",
	"onfocus":                  "Onfocus",
	"onhashchange":             "Onhashchange",
	"onlanguagechange":         "Onlanguagechange",
	"onload":                   "Onload",
	"onmessage":                "Onmessage",
	"onoffline":                "Onoffline",
	"ononline":                 "Ononline",
	"onpopstate":               "Onpopstate",
	"onresize":                 "Onresize",
	"onstorage":                "Onstorage",
	"onunload":                 "Onunload",
	"open":                     "Open",
	"optimum":                  "Optimum",
	"part":                     "Part",
	"pattern":                  "Pattern",
	"ping":                     "Ping",
	"placeholder":              "Placeholder",
	"playsinline":              "Playsinline",
	"popover":                  "Popover",
	"popovertarget":            "Popovertarget",
	"popovertargetaction":      "Popovertargetaction",
	"poster":                   "Poster",
	"preload":                  "Preload",
	"readonly":                 "Readonly",
	"referrerpolicy":           "Referrerpolicy",
	"rel":                      "Rel",
	"required":                 "Required",
	"reversed":                 "Reversed",
	"rows":                     "Rows",
	"rowspan":                  "Rowspan",
	"sandbox":                  "Sandbox",
	"scope":                    "Scope",
	"selected":                 "Selected",
	"shadowrootclonable":       "Shadowrootclonable",
	"shadowrootdelegatesfocus": "Shadowrootdelegatesfocus",
	"shadowrootmode":           "Shadowrootmode",
	"shadowrootserializable":   "Shadowrootserializable",
	"shape":                    "Shape",
	"size":                     "Size",
	"sizes":                    "Sizes",
	"slot":                     "SlotAttr",
	"span":                     "SpanAttr",
	"spellcheck":               "Spellcheck",
	"src":                      "Src",
	"srcdoc":                   "Srcdoc",
	"srclang":                  "Srclang",
	"srcset":                   "Srcset",
	"start":                    "Start",
	"step":                     "Step",
	"style":                    "StyleAttr",
	"tabindex":                 "Tabindex",
	"target":                   "Target",
	"title":                    "TitleAttr",
	"translate":                "Translate",
	"type":                     "Type",
	"usemap":                   "Usemap",
	"value":                    "Value",
	"virtualkeyboardpolicy":    "Virtualkeyboardpolicy",
	"width":                    "Width",
	"wrap":                     "Wrap",
	"writingsuggestions":       "Writingsuggestions",
	"xmlns":                    "Xmlns",
}
