package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/SamHennessy/hlive/hhtml"
)

func generateAttrs() {
	// Create the attrs.go file directly using the structure from DataAll

	f, err := os.Create("./attrs.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	// Write generated file header
	fmt.Fprintln(f, "// Code generated by cmd/attrs/attrs_gen.go - DO NOT EDIT")
	fmt.Fprintln(f, "// Source: hhtml/cmd/attrs/attrs_gen.go")
	fmt.Fprintln(f)

	// Write package declaration and imports
	fmt.Fprintln(f, "package hhtml")
	fmt.Fprintln(f)
	fmt.Fprintln(f, `import "github.com/SamHennessy/hlive"`)
	fmt.Fprintln(f)

	// Get all attribute names from DataAll and sort them
	attrNameMap := make(map[string]bool)
	for _, tagData := range hhtml.DataAll {
		if tagData.Deprecated {
			continue
		}

		for attrName, attrData := range tagData.Attributes {
			if attrName == "data-*" {
				continue
			}

			if attrData.Deprecated {
				continue
			}
			attrNameMap[attrName] = true
		}
	}

	attrNames := make([]string, 0, len(attrNameMap))
	for attrName := range attrNameMap {
		attrNames = append(attrNames, attrName)
	}
	sort.Strings(attrNames)

	attrFunctionNames := make(map[string]string)
	for _, attrName := range attrNames {
		funcName := strings.ToUpper(attrName[:1]) + attrName[1:]
		idx := strings.Index(funcName, "-")
		if idx != -1 {
			funcName = funcName[:idx] + strings.ToUpper(funcName[idx+1:idx+2]) + funcName[idx+2:]
		}

		// Not correct, but fine for this dataset
		if hhtml.TagFunctions[attrName] != nil {
			funcName = funcName + "Attr"
		}

		attrFunctionNames[attrName] = funcName
	}

	// Generate functions for each tag
	for _, attr := range attrNames {
		// Get function name (capitalize first letter)
		funcName := attrFunctionNames[attr]
		shortDesc := fmt.Sprintf("%s represents a %s attribute", funcName, attr)

		// Write function
		fmt.Fprintf(f, "// %s\n", shortDesc)
		fmt.Fprintf(f, "func %s(value string) *hlive.Attribute {\n", funcName)
		fmt.Fprintf(f, "\treturn hlive.NewAttribute(%q, value)\n", attr)
		fmt.Fprintln(f, "}")
		fmt.Fprintln(f)
	}

	// Generate the tag function map
	fmt.Fprintln(f, "// AttrFunctionNames maps attribute names to their corresponding function names")
	fmt.Fprintln(f, "var AttrFunctionNames = map[string]string {")
	for _, attr := range attrNames {
		fmt.Fprintf(f, "\t%q: %q,\n", attr, attrFunctionNames[attr])
	}
	fmt.Fprintln(f, "}")

	fmt.Println("Generated attrs.go successfully!")
}

// Run this function to generate attrs.go
func main() {
	generateAttrs()
}
